use clap::Parser;
use skillmill_core::profile::{StudentProfile, WorksheetCustomisation, WorksheetHeader, WorksheetLayout};

use crate::commands::registry::load_registry;
use crate::ui::prompt;

#[derive(Parser, Debug)]
pub struct InitProfileArgs {
    #[arg(long)]
    pub out: Option<std::path::PathBuf>,
}

pub fn run(args: InitProfileArgs) -> anyhow::Result<()> {
    let registry = load_registry()?;
    let profile = loop {
        let name = prompt::input("Student name")?;
        let disciplines: Vec<String> = registry.ids().map(|s| s.to_string()).collect();
        let discipline_idx = prompt::select("Discipline", &disciplines)?;
        let discipline = disciplines[discipline_idx].clone();

        let plugin = registry.get(&discipline).expect("discipline exists");
        let levels = plugin.curriculum().levels();
        let level_labels: Vec<String> = levels.iter().map(|l| l.0.clone()).collect();
        let level_idx = prompt::select("Level", &level_labels)?;
        let level = &levels[level_idx];

        let mut nodes: Vec<_> = plugin
            .curriculum()
            .nodes
            .values()
            .filter(|n| n.level == *level)
            .collect();
        nodes.sort_by(|a, b| a.id.0.cmp(&b.id.0));
        if nodes.is_empty() {
            return Err(anyhow::anyhow!("no nodes found for level {}", level.0));
        }
        let node_labels: Vec<String> = nodes
            .iter()
            .map(|n| format!("{} — {}", n.id.0, n.label))
            .collect();
        let node_idx = prompt::select("Current node", &node_labels)?;
        let node_id = nodes[node_idx].id.0.clone();

        let working_space_idx = prompt::select(
            "Working space per question",
            &vec!["small".into(), "medium".into(), "large".into()],
        )?;
        let working_space = match working_space_idx {
            0 => "small",
            1 => "medium",
            _ => "large",
        };

        let school = prompt::input_default("School name (optional)", "")?;
        let class = prompt::input_default("Class / group (optional)", "")?;
        let font_size = prompt::input_default("Font size pt", "12")?;
        let font_size: u16 = font_size.parse().unwrap_or(12);

        let profile = StudentProfile {
            name,
            discipline,
            current_node: node_id,
            mastery: std::collections::HashMap::new(),
            customisations: WorksheetCustomisation {
                header: WorksheetHeader {
                    school: if school.trim().is_empty() { None } else { Some(school) },
                    class: if class.trim().is_empty() { None } else { Some(class) },
                    date: "auto".to_string(),
                },
                layout: WorksheetLayout {
                    font_size,
                    working_space: working_space.to_string(),
                },
            },
        };

        println!("\nSummary");
        println!("  Name: {}", profile.name);
        println!("  Discipline: {}", profile.discipline);
        println!("  Node: {}", profile.current_node);
        println!("  Working space: {}", profile.customisations.layout.working_space);
        println!("  School: {}", profile.customisations.header.school.clone().unwrap_or_default());
        println!("  Class: {}", profile.customisations.header.class.clone().unwrap_or_default());
        println!("  Font size: {}", profile.customisations.layout.font_size);

        if prompt::confirm("Confirm profile?", true)? {
            break profile;
        }
    };

    let out_path = args
        .out
        .unwrap_or_else(|| std::path::PathBuf::from("profiles/student.yaml"));
    if let Some(parent) = out_path.parent() {
        std::fs::create_dir_all(parent)?;
    }

    write_profile_with_header(&profile, &out_path)?;
    println!("✓ Created {}", out_path.display());
    println!("  Next: skillmill init policy --profile {}", out_path.display());
    Ok(())
}

fn write_profile_with_header(
    profile: &StudentProfile,
    path: &std::path::Path,
) -> anyhow::Result<()> {
    let mut yaml = serde_yaml::to_string(profile)?;
    yaml = yaml.replace("date: auto", "date: auto  # filled at generation time");
    let mut output = String::new();
    output.push_str("# Generated by: skillmill init profile\n");
    output.push_str(&yaml);
    std::fs::write(path, output)?;
    Ok(())
}
